Resources:
  restaurantsapi89E63B79:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: Restaurant-API
    Metadata:
      aws:cdk:path: CdkWorkshopStack/restaurants-api/Resource
  restaurantsapiDeployment5D689E4A02cf51bcdd7b94a2f66b567f12833bb2:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: restaurantsapi89E63B79
      Description: Automatically created by the RestApi construct
    DependsOn:
      - restaurantsapiGETF9567D45
      - restaurantsapirestaurantsGET74D717AE
      - restaurantsapirestaurants549DE6F1
      - restaurantsapirestaurantssearchGET62595B5A
      - restaurantsapirestaurantssearchCBFC2334
    Metadata:
      aws:cdk:path: CdkWorkshopStack/restaurants-api/Deployment/Resource
  restaurantsapiDeploymentStageprod91712C44:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: restaurantsapi89E63B79
      DeploymentId:
        Ref: restaurantsapiDeployment5D689E4A02cf51bcdd7b94a2f66b567f12833bb2
      StageName: prod
    Metadata:
      aws:cdk:path: CdkWorkshopStack/restaurants-api/DeploymentStage.prod/Resource
  restaurantsapiCloudWatchRoleA0238AA9:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: CdkWorkshopStack/restaurants-api/CloudWatchRole/Resource
  restaurantsapiAccountCC1A0B7E:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - restaurantsapiCloudWatchRoleA0238AA9
          - Arn
    DependsOn:
      - restaurantsapi89E63B79
    Metadata:
      aws:cdk:path: CdkWorkshopStack/restaurants-api/Account
  restaurantsapirestaurants549DE6F1:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - restaurantsapi89E63B79
          - RootResourceId
      PathPart: restaurants
      RestApiId:
        Ref: restaurantsapi89E63B79
    Metadata:
      aws:cdk:path: CdkWorkshopStack/restaurants-api/Default/restaurants/Resource
  restaurantsapirestaurantssearchCBFC2334:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Ref: restaurantsapirestaurants549DE6F1
      PathPart: search
      RestApiId:
        Ref: restaurantsapi89E63B79
    Metadata:
      aws:cdk:path: CdkWorkshopStack/restaurants-api/Default/restaurants/search/Resource
  restaurantsapirestaurantssearchGETApiPermissionCdkWorkshopStackrestaurantsapi7E4903A7GETrestaurantssearchFB43EE71:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - searchRestaurantsHandler79556632
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: restaurantsapi89E63B79
            - /
            - Ref: restaurantsapiDeploymentStageprod91712C44
            - /GET/restaurants/search
    Metadata:
      aws:cdk:path: CdkWorkshopStack/restaurants-api/Default/restaurants/search/GET/ApiPermission.CdkWorkshopStackrestaurantsapi7E4903A7.GET..restaurants.search
  restaurantsapirestaurantssearchGETApiPermissionTestCdkWorkshopStackrestaurantsapi7E4903A7GETrestaurantssearchA5A158E4:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - searchRestaurantsHandler79556632
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: restaurantsapi89E63B79
            - /test-invoke-stage/GET/restaurants/search
    Metadata:
      aws:cdk:path: CdkWorkshopStack/restaurants-api/Default/restaurants/search/GET/ApiPermission.Test.CdkWorkshopStackrestaurantsapi7E4903A7.GET..restaurants.search
  restaurantsapirestaurantssearchGET62595B5A:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId:
        Ref: restaurantsapirestaurantssearchCBFC2334
      RestApiId:
        Ref: restaurantsapi89E63B79
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - searchRestaurantsHandler79556632
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: CdkWorkshopStack/restaurants-api/Default/restaurants/search/GET/Resource
  restaurantsapirestaurantsGETApiPermissionCdkWorkshopStackrestaurantsapi7E4903A7GETrestaurants5C27E857:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - restaurantsHandlerDE4E7F48
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: restaurantsapi89E63B79
            - /
            - Ref: restaurantsapiDeploymentStageprod91712C44
            - /GET/restaurants
    Metadata:
      aws:cdk:path: CdkWorkshopStack/restaurants-api/Default/restaurants/GET/ApiPermission.CdkWorkshopStackrestaurantsapi7E4903A7.GET..restaurants
  restaurantsapirestaurantsGETApiPermissionTestCdkWorkshopStackrestaurantsapi7E4903A7GETrestaurantsC6196E48:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - restaurantsHandlerDE4E7F48
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: restaurantsapi89E63B79
            - /test-invoke-stage/GET/restaurants
    Metadata:
      aws:cdk:path: CdkWorkshopStack/restaurants-api/Default/restaurants/GET/ApiPermission.Test.CdkWorkshopStackrestaurantsapi7E4903A7.GET..restaurants
  restaurantsapirestaurantsGET74D717AE:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId:
        Ref: restaurantsapirestaurants549DE6F1
      RestApiId:
        Ref: restaurantsapi89E63B79
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - restaurantsHandlerDE4E7F48
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: CdkWorkshopStack/restaurants-api/Default/restaurants/GET/Resource
  restaurantsapiGETApiPermissionCdkWorkshopStackrestaurantsapi7E4903A7GET048F412A:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - getIndexFFE07390
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: restaurantsapi89E63B79
            - /
            - Ref: restaurantsapiDeploymentStageprod91712C44
            - /GET/
    Metadata:
      aws:cdk:path: CdkWorkshopStack/restaurants-api/Default/GET/ApiPermission.CdkWorkshopStackrestaurantsapi7E4903A7.GET..
  restaurantsapiGETApiPermissionTestCdkWorkshopStackrestaurantsapi7E4903A7GET2524A4A9:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - getIndexFFE07390
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: restaurantsapi89E63B79
            - /test-invoke-stage/GET/
    Metadata:
      aws:cdk:path: CdkWorkshopStack/restaurants-api/Default/GET/ApiPermission.Test.CdkWorkshopStackrestaurantsapi7E4903A7.GET..
  restaurantsapiGETF9567D45:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId:
        Fn::GetAtt:
          - restaurantsapi89E63B79
          - RootResourceId
      RestApiId:
        Ref: restaurantsapi89E63B79
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - getIndexFFE07390
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: CdkWorkshopStack/restaurants-api/Default/GET/Resource
  getIndexServiceRole8EF3BC7B:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: CdkWorkshopStack/getIndex/ServiceRole/Resource
  getIndexFFE07390:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParametersa498611feca7832279e87264e6d5486ab366796e4fabf129b4d059ee3c7a4eb4S3Bucket6699A798
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersa498611feca7832279e87264e6d5486ab366796e4fabf129b4d059ee3c7a4eb4S3VersionKey5EADC983
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersa498611feca7832279e87264e6d5486ab366796e4fabf129b4d059ee3c7a4eb4S3VersionKey5EADC983
      Handler: index.get
      Role:
        Fn::GetAtt:
          - getIndexServiceRole8EF3BC7B
          - Arn
      Runtime: nodejs10.x
    DependsOn:
      - getIndexServiceRole8EF3BC7B
    Metadata:
      aws:cdk:path: CdkWorkshopStack/getIndex/Resource
      aws:asset:path: asset.a498611feca7832279e87264e6d5486ab366796e4fabf129b4d059ee3c7a4eb4
      aws:asset:property: Code
  restaurantsHandlerServiceRoleC11EB017:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: CdkWorkshopStack/restaurantsHandler/ServiceRole/Resource
  restaurantsHandlerDE4E7F48:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParametersa498611feca7832279e87264e6d5486ab366796e4fabf129b4d059ee3c7a4eb4S3Bucket6699A798
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersa498611feca7832279e87264e6d5486ab366796e4fabf129b4d059ee3c7a4eb4S3VersionKey5EADC983
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersa498611feca7832279e87264e6d5486ab366796e4fabf129b4d059ee3c7a4eb4S3VersionKey5EADC983
      Handler: restaurants.get
      Role:
        Fn::GetAtt:
          - restaurantsHandlerServiceRoleC11EB017
          - Arn
      Runtime: nodejs10.x
    DependsOn:
      - restaurantsHandlerServiceRoleC11EB017
    Metadata:
      aws:cdk:path: CdkWorkshopStack/restaurantsHandler/Resource
      aws:asset:path: asset.a498611feca7832279e87264e6d5486ab366796e4fabf129b4d059ee3c7a4eb4
      aws:asset:property: Code
  searchRestaurantsHandlerServiceRoleBB7FBF1F:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: CdkWorkshopStack/searchRestaurantsHandler/ServiceRole/Resource
  searchRestaurantsHandler79556632:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParametersa498611feca7832279e87264e6d5486ab366796e4fabf129b4d059ee3c7a4eb4S3Bucket6699A798
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersa498611feca7832279e87264e6d5486ab366796e4fabf129b4d059ee3c7a4eb4S3VersionKey5EADC983
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersa498611feca7832279e87264e6d5486ab366796e4fabf129b4d059ee3c7a4eb4S3VersionKey5EADC983
      Handler: restaurants.search
      Role:
        Fn::GetAtt:
          - searchRestaurantsHandlerServiceRoleBB7FBF1F
          - Arn
      Runtime: nodejs10.x
    DependsOn:
      - searchRestaurantsHandlerServiceRoleBB7FBF1F
    Metadata:
      aws:cdk:path: CdkWorkshopStack/searchRestaurantsHandler/Resource
      aws:asset:path: asset.a498611feca7832279e87264e6d5486ab366796e4fabf129b4d059ee3c7a4eb4
      aws:asset:property: Code
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.38.0,@aws-cdk/assets=1.38.0,@aws-cdk/aws-apigateway=1.38.0,@aws-cdk/aws-cloudwatch=1.38.0,@aws-cdk/aws-ec2=1.38.0,@aws-cdk/aws-events=1.38.0,@aws-cdk/aws-iam=1.38.0,@aws-cdk/aws-kms=1.38.0,@aws-cdk/aws-lambda=1.38.0,@aws-cdk/aws-logs=1.38.0,@aws-cdk/aws-s3=1.38.0,@aws-cdk/aws-s3-assets=1.38.0,@aws-cdk/aws-sqs=1.38.0,@aws-cdk/aws-ssm=1.38.0,@aws-cdk/cloud-assembly-schema=1.38.0,@aws-cdk/core=1.38.0,@aws-cdk/cx-api=1.38.0,@aws-cdk/region-info=1.38.0,jsii-runtime=node.js/v12.16.3
    Condition: CDKMetadataAvailable
Outputs:
  restaurantsapiEndpoint831A89FE:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: restaurantsapi89E63B79
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
          - Ref: restaurantsapiDeploymentStageprod91712C44
          - /
Parameters:
  AssetParametersa498611feca7832279e87264e6d5486ab366796e4fabf129b4d059ee3c7a4eb4S3Bucket6699A798:
    Type: String
    Description: S3 bucket for asset "a498611feca7832279e87264e6d5486ab366796e4fabf129b4d059ee3c7a4eb4"
  AssetParametersa498611feca7832279e87264e6d5486ab366796e4fabf129b4d059ee3c7a4eb4S3VersionKey5EADC983:
    Type: String
    Description: S3 key for asset version "a498611feca7832279e87264e6d5486ab366796e4fabf129b4d059ee3c7a4eb4"
  AssetParametersa498611feca7832279e87264e6d5486ab366796e4fabf129b4d059ee3c7a4eb4ArtifactHashA9EBFFC7:
    Type: String
    Description: Artifact hash for asset "a498611feca7832279e87264e6d5486ab366796e4fabf129b4d059ee3c7a4eb4"
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

