Resources:
  widgetsapi0BCA0B12:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: Restaurant-API
    Metadata:
      aws:cdk:path: CdkWorkshopStack/widgets-api/Resource
  widgetsapiDeployment9DE336932a486cea84a9583ae4a07fe848270e6f:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: widgetsapi0BCA0B12
      Description: Automatically created by the RestApi construct
    DependsOn:
      - widgetsapiGETFE8E3A17
      - widgetsapirestaurantsGET22CCF8A5
      - widgetsapirestaurantsEDE71B3B
    Metadata:
      aws:cdk:path: CdkWorkshopStack/widgets-api/Deployment/Resource
  widgetsapiDeploymentStageprod19E45538:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: widgetsapi0BCA0B12
      DeploymentId:
        Ref: widgetsapiDeployment9DE336932a486cea84a9583ae4a07fe848270e6f
      StageName: prod
    Metadata:
      aws:cdk:path: CdkWorkshopStack/widgets-api/DeploymentStage.prod/Resource
  widgetsapiCloudWatchRole13420B98:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: CdkWorkshopStack/widgets-api/CloudWatchRole/Resource
  widgetsapiAccount54650C10:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - widgetsapiCloudWatchRole13420B98
          - Arn
    DependsOn:
      - widgetsapi0BCA0B12
    Metadata:
      aws:cdk:path: CdkWorkshopStack/widgets-api/Account
  widgetsapirestaurantsEDE71B3B:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - widgetsapi0BCA0B12
          - RootResourceId
      PathPart: restaurants
      RestApiId:
        Ref: widgetsapi0BCA0B12
    Metadata:
      aws:cdk:path: CdkWorkshopStack/widgets-api/Default/restaurants/Resource
  widgetsapirestaurantsGETApiPermissionCdkWorkshopStackwidgetsapiE0A045F2GETrestaurants5FB07375:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - restaurantsHandlerDE4E7F48
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: widgetsapi0BCA0B12
            - /
            - Ref: widgetsapiDeploymentStageprod19E45538
            - /GET/restaurants
    Metadata:
      aws:cdk:path: CdkWorkshopStack/widgets-api/Default/restaurants/GET/ApiPermission.CdkWorkshopStackwidgetsapiE0A045F2.GET..restaurants
  widgetsapirestaurantsGETApiPermissionTestCdkWorkshopStackwidgetsapiE0A045F2GETrestaurants49D4C92B:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - restaurantsHandlerDE4E7F48
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: widgetsapi0BCA0B12
            - /test-invoke-stage/GET/restaurants
    Metadata:
      aws:cdk:path: CdkWorkshopStack/widgets-api/Default/restaurants/GET/ApiPermission.Test.CdkWorkshopStackwidgetsapiE0A045F2.GET..restaurants
  widgetsapirestaurantsGET22CCF8A5:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId:
        Ref: widgetsapirestaurantsEDE71B3B
      RestApiId:
        Ref: widgetsapi0BCA0B12
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - restaurantsHandlerDE4E7F48
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: CdkWorkshopStack/widgets-api/Default/restaurants/GET/Resource
  widgetsapiGETApiPermissionCdkWorkshopStackwidgetsapiE0A045F2GET6FDE14E8:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - getIndexFFE07390
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: widgetsapi0BCA0B12
            - /
            - Ref: widgetsapiDeploymentStageprod19E45538
            - /GET/
    Metadata:
      aws:cdk:path: CdkWorkshopStack/widgets-api/Default/GET/ApiPermission.CdkWorkshopStackwidgetsapiE0A045F2.GET..
  widgetsapiGETApiPermissionTestCdkWorkshopStackwidgetsapiE0A045F2GETB6E25ADB:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - getIndexFFE07390
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: widgetsapi0BCA0B12
            - /test-invoke-stage/GET/
    Metadata:
      aws:cdk:path: CdkWorkshopStack/widgets-api/Default/GET/ApiPermission.Test.CdkWorkshopStackwidgetsapiE0A045F2.GET..
  widgetsapiGETFE8E3A17:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId:
        Fn::GetAtt:
          - widgetsapi0BCA0B12
          - RootResourceId
      RestApiId:
        Ref: widgetsapi0BCA0B12
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - getIndexFFE07390
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: CdkWorkshopStack/widgets-api/Default/GET/Resource
  getIndexServiceRole8EF3BC7B:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: CdkWorkshopStack/getIndex/ServiceRole/Resource
  getIndexFFE07390:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParametersbaf37dc8fe7c890417582c777f5f50d5d074821a0992a1aded7491871fda9634S3BucketB27AE360
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersbaf37dc8fe7c890417582c777f5f50d5d074821a0992a1aded7491871fda9634S3VersionKey9378E378
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersbaf37dc8fe7c890417582c777f5f50d5d074821a0992a1aded7491871fda9634S3VersionKey9378E378
      Handler: index.get
      Role:
        Fn::GetAtt:
          - getIndexServiceRole8EF3BC7B
          - Arn
      Runtime: nodejs10.x
    DependsOn:
      - getIndexServiceRole8EF3BC7B
    Metadata:
      aws:cdk:path: CdkWorkshopStack/getIndex/Resource
      aws:asset:path: asset.baf37dc8fe7c890417582c777f5f50d5d074821a0992a1aded7491871fda9634
      aws:asset:property: Code
  restaurantsHandlerServiceRoleC11EB017:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: CdkWorkshopStack/restaurantsHandler/ServiceRole/Resource
  restaurantsHandlerDE4E7F48:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParametersbaf37dc8fe7c890417582c777f5f50d5d074821a0992a1aded7491871fda9634S3BucketB27AE360
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersbaf37dc8fe7c890417582c777f5f50d5d074821a0992a1aded7491871fda9634S3VersionKey9378E378
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersbaf37dc8fe7c890417582c777f5f50d5d074821a0992a1aded7491871fda9634S3VersionKey9378E378
      Handler: restaurants.get
      Role:
        Fn::GetAtt:
          - restaurantsHandlerServiceRoleC11EB017
          - Arn
      Runtime: nodejs10.x
    DependsOn:
      - restaurantsHandlerServiceRoleC11EB017
    Metadata:
      aws:cdk:path: CdkWorkshopStack/restaurantsHandler/Resource
      aws:asset:path: asset.baf37dc8fe7c890417582c777f5f50d5d074821a0992a1aded7491871fda9634
      aws:asset:property: Code
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.38.0,@aws-cdk/assets=1.38.0,@aws-cdk/aws-apigateway=1.38.0,@aws-cdk/aws-cloudwatch=1.38.0,@aws-cdk/aws-ec2=1.38.0,@aws-cdk/aws-events=1.38.0,@aws-cdk/aws-iam=1.38.0,@aws-cdk/aws-kms=1.38.0,@aws-cdk/aws-lambda=1.38.0,@aws-cdk/aws-logs=1.38.0,@aws-cdk/aws-s3=1.38.0,@aws-cdk/aws-s3-assets=1.38.0,@aws-cdk/aws-sqs=1.38.0,@aws-cdk/aws-ssm=1.38.0,@aws-cdk/cloud-assembly-schema=1.38.0,@aws-cdk/core=1.38.0,@aws-cdk/cx-api=1.38.0,@aws-cdk/region-info=1.38.0,jsii-runtime=node.js/v12.16.3
    Condition: CDKMetadataAvailable
Outputs:
  widgetsapiEndpoint2B78C075:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: widgetsapi0BCA0B12
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
          - Ref: widgetsapiDeploymentStageprod19E45538
          - /
Parameters:
  AssetParametersbaf37dc8fe7c890417582c777f5f50d5d074821a0992a1aded7491871fda9634S3BucketB27AE360:
    Type: String
    Description: S3 bucket for asset "baf37dc8fe7c890417582c777f5f50d5d074821a0992a1aded7491871fda9634"
  AssetParametersbaf37dc8fe7c890417582c777f5f50d5d074821a0992a1aded7491871fda9634S3VersionKey9378E378:
    Type: String
    Description: S3 key for asset version "baf37dc8fe7c890417582c777f5f50d5d074821a0992a1aded7491871fda9634"
  AssetParametersbaf37dc8fe7c890417582c777f5f50d5d074821a0992a1aded7491871fda9634ArtifactHash7B4B6794:
    Type: String
    Description: Artifact hash for asset "baf37dc8fe7c890417582c777f5f50d5d074821a0992a1aded7491871fda9634"
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

